### ISSUE TITLE
Rename-project won't run by default

### ISSUE THREAD

**Issue by jdobruchowski** [rochacbruno/python-project-template#20]
**Describe the bug**
Action  Rename-project won't run without elevating workflow permissions 

**To Reproduce**
Click the link in readme ( https://github.com/rochacbruno/python-project-template/generate ) 
Name the project
Go into actions and error should be there

**Expected behavior**
AFAIK this can not be worked around. Probably update readme so newbs like me don't spend 30 minutes hunting git docs for a solution. I have like 1 hour of work experience in GitHub so can't advise how it should be solved.

**Error Log**
remote: Permission to jdobruchowski/Oracle-REST-SQL-util-.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/jdobruchowski/Oracle-REST-SQL-util-/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

**Comment by rochacbruno** [comment]
Looks like this is due to some recent changes on github actions permissions, I will investigate.

**Comment by rochacbruno** [comment]
Fixed, 

added `permissions: write-all` to the workflow file
